<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fei</string>
		<string>essi</string>
	</array>
	<key>foldingStartMarker</key>
	<string>.*[^;]|{</string>
	<key>foldingStopMarker</key>
	<string>;|}</string>
	<key>name</key>
	<string>fei</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>If </string>
			<key>match</key>
			<string>if|while|else</string>
			<key>name</key>
			<string>keyword.control.fei</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FEI reserved keywords (first level)</string>
			<key>match</key>
			<string>\b()\b</string>
			<key>name</key>
			<string>keyword.other.fei</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>These are keywords which change within similar commands. So called second level keywords.</string>
			<key>match</key>
			<string>\b(20NodeBrick|20NodeBrick_elastic|20NodeBrick_upU|27NodeBrick|27NodeBrick_elastic|27NodeBrickLT|3NodeShell_ANDES|4NodeShell_ANDES|4NodeShell_MITC4|4NodeShell_NewMITC4|8NodeBrick|8NodeBrick_elastic|8NodeBrick_up|8NodeBrick_upU|8NodeBrickLT|beam_9dof_elastic|beam_displacement_based|beam_elastic|beam_elastic_lumped_mass|Caughey3rd|Caughey4th|DruckerPragerLT|Energy_Increment|Euler_One_Step|Euler_Multistep|Modified_Euler_Error_Control|Runge_Kutta_45_Error_Control|Backward_Euler|FrictionalPenaltyContact|from_reactions|Hilber_Hughes_Taylor|linear|linear_elastic_crossanisotropic|linear_elastic_isotropic_3d|linear_elastic_isotropic_3d_LT|Modified_Newton|Mx|My|Mz|Newmark|Newton|Norm_Displacement_Increment|Norm_Unbalance|path_series|path_time_series|PisanoLT|ProfileSPD|Rayleigh|sanisand2004|sanisand2008|ShearBeamLT|static|transient|truss|UMFPack|uniaxial_concrete02|uniaxial_elastic|uniaxial_steel01|uniaxial_steel02|variable transient|VonMisesLT|With_no_convergence_check)\b</string>
			<key>name</key>
			<string>constant.other.fei</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers like 1, 1.0, 1.2e2, 1.2e+3, 1.2e-3, .1, .1e+3, .1e-3, .1e2</string>
			<key>match</key>
			<string>[0-9]+\.[0-9]*([Ee][-+]?[0-9]+)?|(\.)?[0-9]+([Ee][-+]?[0-9]+)?</string>
			<key>name</key>
			<string>constant.numeric.fei</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Strings</string>
			<key>match</key>
			<string>(")+(.*)(")+</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fei</string>
	<key>uuid</key>
	<string>f2c2f4ff-2592-4649-b8ba-3ecf8faaf57c</string>
</dict>
</plist>
